version: '3.8'

services:
  structurizr:
    image: structurizr/lite
    container_name: structurizr_lite
    ports:
      - "8000:8080"
    volumes:
      - ./architecture:/usr/local/structurizr
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: admin_system.dockerfile
    container_name: admin
    restart: always
    ports:
      - "8001:8000"

  passenger:
    build:
      context: .
      dockerfile: account_system_passenger.dockerfile
    container_name: passenger
    restart: always
    ports:
      - "8002:8000"

  driver:
    build:
      context: .
      dockerfile: account_system_driver.dockerfile
    container_name: driver
    restart: always
    ports:
      - "8003:8000"

  adding_trips:
    build:
      context: .
      dockerfile: driver_system_adding_trip.dockerfile
    container_name: adding_trips
    restart: always
    ports:
      - "8004:8000"

  connect_trips:
    build:
      context: .
      dockerfile: driver_system_connect_trip.dockerfile
    container_name: connect_trips
    restart: always
    ports:
      - "8005:8000"

